#+DATE: <2020-08-04 Tue 16:39>
#+TITLE: Idea

* 闪念

** [2021-07-19 Mon 10:22]

时间是自己的，浪费了就没有了，所以效率是应该时刻注意的方面。利己固然不是错的，但利他更是有必要的，人不是生活在孤塔之中，自然不能活得狭隘，正所谓“心底无私天地宽”，“夫唯不居，是以不去”。

** [2021-07-19 Mon 09:28]

#+BEGIN_QUOTE
什么事情，没做决定的时候，怎么都难，真到做了决定之后，反而容易了。 -- 毛主席
#+END_QUOTE 

** [2021-07-18 Sun 21:04]

没有什么是容易的，应该不断实现自我的革新。保持思考，保持清醒！

** [2021-07-14 Wed 17:37]

文章配图真的是一个烦人的问题……

** [2021-07-12 Mon 10:11]

#+BEGIN_QUOTE
“是绝望！因为绝望，他们放浪形骸，纵情声色。因为绝望，他们一掷千金，旷达不羁。因为绝望，他们只醉今朝，不求来日！” -- 《山海八荒录》
#+END_QUOTE

** [2021-07-08 Thu 16:08]

有些事，一旦习惯了，就习惯了。

** [2021-06-21 Mon 10:03]

再高深的思想，离开了具体的行动，也是空中楼阁。只有切实地去执行内心的想法和计划，才会真正地对自然、社会进行改造。行动不应该是盲动的，应该在科学的理论指导下进行，并根据实际情况进行修正。

** [2021-06-02 Wed 16:02]

有时候，我们总是重复性地做一些毫无意义的事情，绝对的强迫症晚期！

** [2021-05-19 Wed 15:59]

所有的认识论，要想对社会进行有效的改造，最终都要归结到四个字 - *实事求是* ！

** [2021-05-19 Wed 11:43]

又换域名了，强迫症……

** [2021-05-19 Wed 11:24]

长期、中期、短期规划缺一不可！！！

** [2021-05-08 Sat 10:26]

想法再奇妙，离开了实实在在的行动，也是徒劳。

** [2021-02-04 Thu 09:01]

知更所知，求知所不知，知也。

** [2021-02-02 Tue 10:19]

"Any intelligent fool can make things bigger, more complex, and more violent. It takes a touch of genius - and a lot of courage - to move in the opposite direction." -- Albert Einstein

** [2021-01-30 Sat 16:18]

实践是检验真理的唯一标准！！！

** [2020-12-11 Fri 10:18]

是什么？做什么？为什么？怎么做？优、缺 。

** [2020-11-11 Wed 09:59]

光阴似箭，时不我待。

** [2020-11-11 Wed 09:12]

生命不息，读书不止。立足实践，学以致用。循序渐进，持之以恒。

** [2020-10-06 Tue 09:20]

疏密得当，形继神连。

** [2020-09-03 Thu 14:31]

事物的发展是有一个过程的，没有对现象的具体了解，就没有对本质的抽象认识。

** [2020-08-31 Mon 08:24]

成就你的将束缚你，束缚你的也终将成就你。

