#+DATE: <2020-09-15 Tue 21:49>
#+TITLE: Joker

#+BEGIN_EXPORT html
<div style="
color: #ccc;
background-image: linear-gradient(to right, red, orange, yellow, green, yellow, orange, red, orange, yellow, green, yellow, orange, red);
-webkit-background-clip: text;
animation: move 5s infinite;
color: transparent;
">
生活就像一场滑稽的舞台剧，往往到最后才发现台上的小丑是自己……
</div>

<style>
@keyframes move {
0% {background-position: 0 0;}
50% {
background-position: -500px 0;
}
100% {background-position: 0 0;}}
</style>
#+END_EXPORT

* JOKER

** [2021-06-14 Mon 22:12]

人生应该活得精彩！如何才算精彩？如何才能精彩呢？

私以为，人要活得精彩，首先要得自由。自由？心无挂牵也，无束缚也。

人活于世，能无牵挂乎？人皆有父母，父母在世者，不能不念父母之哀喜，然父母之欣与己念必相反乎？否也！父母之心，皆欲子顺遂，而苦其逆。无论心念几何，当思父母之不易，为其多虑一二也。

未结……

** [2021-06-07 Mon 09:30]

又是周一，为什么是“又”呢？因为生活在重复……

生活应该精致一点，不是说“小资”，而是各个方面要有益身心，科学地提升生活的品质。一个有意识的人，要做到真正的无欲无求太难了，所谓的“无欲无求”本身也是一种欲求……

一个人不可能无欲无求！上善若水，真正的自然乃是不自知。合理化欲求，身体力行！

** [2021-06-02 Wed 14:42]

这生活可真是够无聊的了，像是在一个迷宫里来回的打转，找不到出口在哪边……

网络小说是不能再开新坑了，没什么营养，无限副本和流水账，浪费时间和精力，有那闲功夫，自己去着手写一本反而是更好的选择，起码还能练练打字。

生活和工作像一团乱麻，剪不断，理还乱，莫名其妙地就失去了重心和着手点。绝对不是没有事情可以做，但又的确明明白白地不知道应该做什么，真是见了鬼了。

事情，是不可能一蹴而就的，必须是有计划的。

#+BEGIN_QUOTE
孔夫子说：“吾十有五而志于学，三十而立，四十而不惑，五十而知天命，六十而耳顺，七十而从心所欲不逾矩。”
#+END_QUOTE

“从心所欲不逾矩”真的是吾辈梦寐以求，是一种心灵的自由。生活中充满了很多的无奈，你可能会碰见很多的迷惑和不解（可傻B的事情） 。但是有一点是可以做到的，就是控制你自己，是的，总能控制你自己。

不可控的感觉真的是让人不禁发狂，太多的不可控会以极快的速度消耗一个人的精神和耐力。我应该是没有暴力倾向的人，耐心确是不够的。

#+BEGIN_EXPORT html
<note>
我不讨厌小孩子，但是讨厌带小孩子，对于熊孩子，连想想都忍不住想揍他们一顿。

<p>公司一人天天带孩子上班，每次见了之后都烦的要死，其实又碍着自己什么事儿了，感觉可傻比……</p>
</note>
#+END_EXPORT

说到这里，不由想起《天下第一》中铁胆神侯，明里一套，暗里一套，把自己做的坏事都写在日记中，才能排解内心的苦闷，我到是没有做过什么坏事，或多或少却总有些情景类似和代入。

要整理一下生活，好好思考一下明天的路该往哪边走！除却自己，他人之思绪皆是无谓来哉。

** [2021-05-31 Mon 10:50]

改变是辛苦的，但确是有意义的。

有些技能没必要完全掌握，有个大概了解就可以了，但有些领域却不能浅尝辄止，不仅是要掌握，而且必须相当熟练、如臂使指。比如说，一个剑客应该绝对了解自己的剑，一个赛车手应该绝对了解自己的车，一个程序员应该绝对了解自己的键盘和电脑……

现在的问题恰恰在于，该熟练掌握的技能还有很多的不足之处，术法不精。改善！需要不断精进、持之以恒地努力。

一个没有活力的环境是可怕的，它让人很容易地陷入怠惰之中。安逸的环境是不可持久的，变化随时而来，未雨绸缪是很有必要的。

如果你要做什么，首先应该有一个计划，然后，围绕计划制定具体的、可执行的行动，并且身体力行。

思考、领悟！

** [2021-05-25 Tue 11:13]

最近几周不知道怎么了，总是无精打采的，没有了活力……

生活没有了方向，前行的每一步都感觉是如此的沉重，像是走在泥泞的沼泽，满身的疲惫。这绝对不是身体的辛苦，是精神！内心的愤懑、不甘，像是随波逐流的舟子，漂浮在宿命的长河之中。

再华丽的文字也掩饰不住内心的空虚，就像现在这样，生活就像是一出滑稽的舞台剧，在台下笑的前俯后仰，最后却卑哀地发现台上的小丑竟然是自己……

读书少的结果就是，你能被心中的繁杂堵死，千言万语不晓得如何排解。然而，人总不能真的把自己憋死？

学无止境！其实有好多东西需要去学习，只是懒得去行动，为什么呢？好似做些有真正有意义的事情比无聊的打发时间还来的无趣。凡夫俗子，长则不过百年光阴，之后数载便成了一抔黄土，最终永远的消失在历史的长河之中，没有任何的痕迹。

时间和精力是有限的，生活当是以人为本，而不是无谓的消耗。比如现下比较流行的手机依赖症，有事儿没事地就要滑一下手机，要是哪天手机没有了电量，又没有充电的地方，整个人都变得不好了。人不再是手机的使用者，反而沦为了它的奴隶。自然，都如此了，身心都越来越不济，就更不要妄谈可以收获到什么快乐了。

你到底是要和自己说话，还是要把心里的话说给别人听，让他人也感受着你的喜怒哀乐。然而，情绪终究是一个人的，真正的秘密又岂是轻易愿意与人诉说的。心里的话，最多也只是诉诸于文字笔端，整理下琐碎繁杂的思绪罢了。

……
